// <auto-generated />
using System;
using ArtistsInResidency.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtistsInResidency.Migrations
{
    [DbContext(typeof(ArtistDbContext))]
    partial class ArtistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("ArtistsInResidency.Models.ArtModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArtistModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(300);

                    b.Property<string>("medium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("yearCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ArtistModelid");

                    b.ToTable("worksOfArt");
                });

            modelBuilder.Entity("ArtistsInResidency.Models.ArtistModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.HasKey("id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("ArtistsInResidency.Models.ArtModel", b =>
                {
                    b.HasOne("ArtistsInResidency.Models.ArtistModel", null)
                        .WithMany("associatedWorks")
                        .HasForeignKey("ArtistModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
